/**
 * MorbiusChatAgent — generates real conversational replies via NVIDIA
 * NIM (with HF + Ollama cascade fallback). Fires when triage flags
 * the patient turn as conversational / small-talk / vague-exploratory.
 *
 * Why a separate agent: the diagnostic agent emits structured-JSON
 * differentials. For a "hello doc" or "good morning" or "tell me
 * about you", we want a 1-3 sentence warm-doctor reply generated by
 * the model, not a canned acknowledgement or a 5-question SOAP form.
 *
 * Pre-built strings stay as a last-resort fallback only — if every
 * backend is down, the user still sees a sensible reply rather than
 * an error wall.
 */

import { BaseAgent } from '@dr-abc/morbius-core';
import {
  AgentKind,
  Intent,
  type OrchestratorEvent,
  type Task,
  type TaskContext,
} from '@dr-abc/types';

export interface ChatInput {
  /** Raw user turn. */
  text: string;
  /** Optional priors from triage so the chat reply matches mood. */
  redFlags?: string[];
  esi?: number;
}

export interface ChatOutput {
  /** Generated reply, 1-3 short sentences in warm-doctor voice. */
  reply: string;
  /** Which backend produced the reply. */
  modelUsed: string;
}

const REQUEST_TIMEOUT_MS = 35_000;

const BASE_SYSTEM_PROMPT = `You are Mörbius — a real doctor talking with a real patient in their living room. Not a chatbot. Not a clinical questionnaire. A doctor who actually listens.

THE HARD RULES (these matter most):

1. NEVER INVENT WHAT THE PATIENT DIDN'T SAY. The patient's text is the WHOLE context — nothing else. Do not infer "history of anxiety" from a glucose reading. Do not claim they have "persistent worry" if they only mentioned a lab value. Do not add "you mentioned sleep disruption" unless they literally typed those words. If you don't have data, don't make it up — just ask for it.

2. ONE question at a time. Never a numbered list. Never bullet 3-5 follow-ups. A real doctor leans forward and asks the SINGLE most diagnostically useful thing. Save the rest for the next turn.

3. Reply length: 2-3 short sentences. Never a wall of text.

GOOD example for "My fasting glucose has been 180 — should I worry?":
  "Yes, a fasting glucose of 180 is high enough to take seriously — it's consistent with diabetes, though one reading alone isn't a diagnosis. Was this a true fasting reading, meaning you hadn't eaten or drunk anything but water for at least 8 hours beforehand?"

BAD example (DO NOT DO THIS):
  "I can see you're concerned about your glucose level being 180, and given your history of anxiety and sleep disruption, this is likely related to type 2 diabetes. Can you tell me about your panic attacks?"
  (Bad because: patient never mentioned anxiety, sleep, or panic attacks. The doctor invented context.)

How you talk:
- Plain conversational prose. No markdown headers, no bullets, no JSON, no "Here are the questions you should consider". Just talk.
- Name the likely condition in plain language ("type 2 diabetes" not "T2DM E11.9"). Use clinical hedges ("likely", "consistent with", "I'd want to confirm with…") never definitive claims.
- For greetings or small-talk: match warmth, invite one share, stop.
- Red-flag language ("crushing chest pain", "worst headache", "I want to die") is NEVER minimised — say "this sounds urgent" and direct to emergency (112 / 911) in the next sentence.
- If the patient writes in German, reply in German. Hindi gets Hindi. Match the patient's language always.
- Never start with "As an AI…", "I'm just a language model…", or any other software-apology hedge. You're a doctor.`;

/**
 * Pick the right salutation for the wall-clock time. Fixes a bug where
 * Mörbius said "good morning" at 16:00 local because the model wasn't
 * told what time of day it was, so
 * it defaulted to morning. We now inject the time-of-day into the
 * system prompt so a 4 PM "hello doc" gets "good afternoon" back.
 */
function timeOfDay(now: Date = new Date()): 'morning' | 'afternoon' | 'evening' | 'night' {
  const h = now.getHours();
  if (h >= 5 && h < 12) return 'morning';
  if (h >= 12 && h < 17) return 'afternoon';
  if (h >= 17 && h < 22) return 'evening';
  return 'night';
}

function buildSystemPrompt(now: Date = new Date()): string {
  const tod = timeOfDay(now);
  const hh = String(now.getHours()).padStart(2, '0');
  const mm = String(now.getMinutes()).padStart(2, '0');
  return [
    BASE_SYSTEM_PROMPT,
    `Current local time: ${hh}:${mm} (${tod}). When greeting, match the time of day — say "good ${tod}" only if it's actually ${tod}; never say "good morning" in the afternoon or evening.`,
  ].join(' ');
}

export { timeOfDay };

export class MorbiusChatAgent extends BaseAgent<ChatInput, ChatOutput> {
  readonly kind = AgentKind.Chat;
  readonly version = '0.1.0';
  readonly minConfidence = 0.5;

  canHandle(task: Task): boolean {
    // Conversational intents land here directly. Triage can also
    // chain into chat by emitting `suggestedNextAgent: 'chat'` when
    // the input is vague + non-clinical.
    return (
      task.intent === Intent.GeneralChat ||
      task.intent === Intent.Ambiguous ||
      task.intent === Intent.ReadAbout ||
      task.intent === Intent.DrugQuery
    );
  }

  protected async reason(
    task: Task<ChatInput>,
    emit: (e: OrchestratorEvent) => void,
  ): Promise<{
    data: ChatOutput;
    confidence: number;
    evidence: string[];
    warnings: string[];
  }> {
    const input = task.payload as ChatInput | { text: string; clarifyingQuestions?: string[] };
    const incomingText = 'text' in input ? input.text : '';
    const clarifyingQuestions = (input as { clarifyingQuestions?: string[] }).clarifyingQuestions;

    // Strip the KG grounding block — the orchestrator prepends a
    // `KNOWN CONTEXT FROM MÖRBIUS'S BRAIN:\n...\n\n---\n\n<patient>` wrapper
    // for the diagnostic agent's benefit (it wants the graph evidence
    // before reasoning). But for the chat clarification turn, that
    // wrapper IS the bleed: the LLM reads it as patient context and
    // reflects seed-case narratives ("HR 138, AFib") instead of the
    // patient's actual words ("PCOS"). For chat, we always want the
    // raw text after the `---` sentinel. Verified bug 2026-05-13:
    // patient typed "irregular periods + acne — could it be PCOS?",
    // graph activated atrial-fibrillation via the word "irregular",
    // chat replied with HR 138 + AFib boilerplate.
    const SENTINEL = '\n\n---\n\n';
    const rawUserText = incomingText.includes(SENTINEL)
      ? (incomingText.split(SENTINEL).pop() ?? incomingText).trim()
      : incomingText;

    // Design intent: surface actual responses from Mörbius in
    // consultation. Triage's clarifying questions are a generic
    // dermatology-flavored boilerplate — they don't fit a PCOS or
    // headache prompt. So we ignore the canned list and have the LLM
    // generate 2-3 context-AWARE follow-up questions based on the
    // actual patient text. The LLM is a 70b doctor; trust it.
    // The consult should read as a doctor-patient chat, not directly
    // the NVIDIA response. When triage flags this
    // turn as needing clarification, we IGNORE the canned generic
    // questions array (which is mental-health-flavoured boilerplate
    // and leaks themes like 'anxiety' / 'sleep disruption' into the
    // LLM's reflection) and feed the LLM only the raw user text plus
    // a strict conversational instruction. The LLM picks its own
    // follow-up question based on the actual clinical presentation.
    // Observed failure mode: the LLM was inventing "chest
    // pain after meals" and "weight loss" for a patient who only
    // typed "nausea + vomits water in the morning for 2 weeks". A
    // simple "don't invent" rule wasn't enough — temperature lowered
    // to 0.25 AND the prompt now hands the LLM a forced reflection
    // scaffold that names ONLY what was actually said before the
    // model is allowed to speculate.
    const userText =
      clarifyingQuestions && clarifyingQuestions.length > 0
        ? `PATIENT-SAID-VERBATIM: "${rawUserText}"

INSTRUCTIONS:
You are their doctor. Reply in exactly this conversational shape (no headers, no bullets — just talk):

[Sentence 1] Reflect what they said using ONLY words and concepts from PATIENT-SAID-VERBATIM. Example: if they said "nausea and vomiting water in the morning for 2 weeks", you say "So you've had nausea and morning vomiting of water for about two weeks." NEVER add new symptoms (chest pain, weight loss, anxiety, sleep problems, etc.) unless the patient typed them.

[Sentence 2] Name the likely condition family in plain language ("could be a stomach issue like acid reflux or gastritis"). Hedge with "could be" or "consistent with" — never "you have."

[Sentence 3] Ask ONE specific follow-up question that a real clinician would ask next for THIS exact presentation. One question. No numbered lists.

If anything in your reply is not directly supported by PATIENT-SAID-VERBATIM, delete it before responding.`
        : rawUserText;

    // Stream tokens through `emit` so the consult UI can render
    // reply text as it arrives, not after the full completion. This
    // addresses a "response is too late" latency issue — a
    // 70b NIM cold start is 5-15 s and the UI used to sit blank
    // until the whole reply was JSON-decoded.
    const onDelta = (delta: string) => {
      if (!delta) return;
      emit({ type: 'agent.token', agent: this.kind, token: delta });
    };

    // Try streaming first — gives the live-typing feel when NIM /
    // HF support it. If streaming returns nothing usable (NVIDIA
    // occasionally 4xx's the SSE accept header on cold-start), fall
    // back to the non-streaming endpoint and emit the whole reply
    // as a single delta so the UI still gets a real LLM response.
    let result = await tryNvidiaStreaming(userText, onDelta).catch(() => null);
    if (!result) {
      const nonStreaming = await tryNvidia(userText, task.context).catch(() => null);
      if (nonStreaming) {
        onDelta(nonStreaming.reply);
        result = nonStreaming;
      }
    }
    if (result) {
      return {
        data: { reply: result.reply, modelUsed: result.modelUsed },
        confidence: 0.85,
        evidence: [`backend:${result.modelUsed}`],
        warnings: [],
      };
    }

    let hf = await tryHuggingFaceStreaming(userText, onDelta).catch(() => null);
    if (!hf) {
      const nonStreaming = await tryHuggingFace(userText, task.context).catch(() => null);
      if (nonStreaming) {
        onDelta(nonStreaming.reply);
        hf = nonStreaming;
      }
    }
    if (hf) {
      return {
        data: { reply: hf.reply, modelUsed: hf.modelUsed },
        confidence: 0.75,
        evidence: [`backend:${hf.modelUsed}`],
        warnings: [],
      };
    }

    // Last-resort canned fallback so a fully-offline demo machine
    // still produces a reasonable reply. Never the primary path.
    const fallback = fallbackReply(userText, task.context.locale ?? 'en-US');
    onDelta(fallback);
    return {
      data: { reply: fallback, modelUsed: 'fallback' },
      confidence: 0.4,
      evidence: ['backend:fallback'],
      warnings: ['all-cascade-backends-unavailable'],
    };
  }
}

interface ChatBackendResult {
  reply: string;
  modelUsed: string;
}

async function tryNvidia(text: string, _context: TaskContext): Promise<ChatBackendResult | null> {
  const apiKey = process.env.NVIDIA_API_KEY;
  if (!apiKey) return null;
  const model = process.env.NVIDIA_MODEL ?? 'meta/llama-3.3-70b-instruct';
  const res = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: buildSystemPrompt() },
        { role: 'user', content: text },
      ],
      max_tokens: 180,
      temperature: 0.25,
    }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!res.ok) return null;
  const json = (await res.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const reply = json.choices?.[0]?.message?.content?.trim();
  if (!reply) return null;
  return { reply, modelUsed: `nvidia:${model}` };
}

/**
 * Streaming variant of `tryNvidia` — uses the OpenAI-compatible
 * server-sent-events API on integrate.api.nvidia.com. Each delta
 * is pushed to `onDelta` so the consult page can render the reply
 * as it's produced (kills the dead air during a 70b cold start).
 *
 * Returns the full concatenated reply once the stream closes, so
 * the agent's `data.reply` matches what was actually produced.
 */
async function tryNvidiaStreaming(
  text: string,
  onDelta: (delta: string) => void,
): Promise<ChatBackendResult | null> {
  const apiKey = process.env.NVIDIA_API_KEY;
  if (!apiKey) return null;
  const model = process.env.NVIDIA_MODEL ?? 'meta/llama-3.3-70b-instruct';
  const res = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      Accept: 'text/event-stream',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: buildSystemPrompt() },
        { role: 'user', content: text },
      ],
      max_tokens: 180,
      temperature: 0.25,
      stream: true,
    }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!res.ok || !res.body) return null;
  const reply = await consumeOpenAIStream(res.body, onDelta);
  if (!reply) return null;
  return { reply, modelUsed: `nvidia:${model}` };
}

/**
 * Read an OpenAI-compatible SSE stream (`data: {"choices":[{"delta":
 * {"content":"…"}}]}` lines, terminated by `data: [DONE]`) and call
 * `onDelta` for each content chunk. Returns the joined reply.
 */
async function consumeOpenAIStream(
  body: ReadableStream<Uint8Array>,
  onDelta: (delta: string) => void,
): Promise<string> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  let full = '';
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop() ?? '';
    for (const raw of lines) {
      const line = raw.trim();
      if (!line.startsWith('data:')) continue;
      const payload = line.slice(5).trim();
      if (!payload || payload === '[DONE]') continue;
      try {
        const ev = JSON.parse(payload) as {
          choices?: Array<{ delta?: { content?: string }; message?: { content?: string } }>;
        };
        const delta = ev.choices?.[0]?.delta?.content ?? ev.choices?.[0]?.message?.content;
        if (delta) {
          full += delta;
          onDelta(delta);
        }
      } catch {
        // malformed event — skip
      }
    }
  }
  return full.trim();
}

/** Streaming variant of HF chat completions — same OpenAI-compatible SSE. */
async function tryHuggingFaceStreaming(
  text: string,
  onDelta: (delta: string) => void,
): Promise<ChatBackendResult | null> {
  const token = process.env.HF_API_TOKEN;
  if (!token) return null;
  const model = process.env.HF_MODEL ?? 'aaditya/Llama3-OpenBioLLM-8B';
  const res = await fetch('https://router.huggingface.co/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'text/event-stream',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: buildSystemPrompt() },
        { role: 'user', content: text },
      ],
      max_tokens: 180,
      temperature: 0.25,
      stream: true,
    }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!res.ok || !res.body) return null;
  const reply = await consumeOpenAIStream(res.body, onDelta);
  if (!reply) return null;
  return { reply, modelUsed: `huggingface:${model}` };
}

async function tryHuggingFace(
  text: string,
  _context: TaskContext,
): Promise<ChatBackendResult | null> {
  const token = process.env.HF_API_TOKEN;
  if (!token) return null;
  const model = process.env.HF_MODEL ?? 'aaditya/Llama3-OpenBioLLM-8B';
  const res = await fetch('https://router.huggingface.co/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: buildSystemPrompt() },
        { role: 'user', content: text },
      ],
      max_tokens: 180,
      temperature: 0.25,
    }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!res.ok) return null;
  const json = (await res.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const reply = json.choices?.[0]?.message?.content?.trim();
  if (!reply) return null;
  return { reply, modelUsed: `huggingface:${model}` };
}

function fallbackReply(text: string, locale: string): string {
  const de = locale.toLowerCase().startsWith('de');
  const tod = timeOfDay();
  const enSalute = tod === 'night' ? 'Hello there' : `Good ${tod}`;
  const deSalute = (() => {
    if (tod === 'morning') return 'Guten Morgen';
    if (tod === 'afternoon') return 'Guten Tag';
    if (tod === 'evening') return 'Guten Abend';
    return 'Hallo';
  })();
  if (/^(hi|hello|hey|good\s+(morning|afternoon|evening|night))\b/i.test(text.trim())) {
    return de
      ? `${deSalute}. Schön, dass Sie da sind. Was beschäftigt Sie heute?`
      : `${enSalute}. Good to hear from you — what's on your mind today?`;
  }
  return de
    ? 'Erzählen Sie mir mehr — was möchten Sie besprechen?'
    : 'Tell me a little more about what brought you here today.';
}
